function debug(message){if(DEBUG===true){console.log(message);}}
function ajax_it(url,data,data_type){return $.ajax({"header":{"User-Agent":"	Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.15) Gecko/20110303  Firefox/3.6.15","X-Alt-Referer":document.location.href},"url":url,"data":data,"cache":false,"dataType":data_type});}
function clear_subdomain(hosts){if(/mypagediy|17t17p|livdig/.test(hosts)===true){hosts.shift();}
if(hosts.length>=4){for(var i=0;i<hosts.length-3;i++){hosts.shift();}}
return hosts;}
function fix_prefix_class_name(class_name){if(/[0-9]/.test(class_name[0])==true){class_name="map_"+class_name;}
return class_name;}
var map_17t17p_com=function(){debug('Init 17t17p_com class');this.run=function(){debug('Strat run');var pid=$("table[id]:eq(0)").attr("id").replace("pid","");$("#postmessage_"+pid).html($("#display_infos").html());debug("Not Ajax just hidden content & Changed Content");}};var akzone_com_hk=function(){debug("Init akzone_com_hk class");this.run=function(){debug("Start run");var url=window.location.href;var id=url.match(/id=(\d+)/)[1];debug("URL: "+url)
debug("ID: "+id)
$.get("http://"+window.location.host+"/fb_like.php",{"zone":"forum","id":id,"url":url},function(html){window.location.reload();});}};var easybuzzz_fr=function(){debug("Init easybuzzz_fr class");this.run=function(){debug("Start run");var lines=$("script:not(script[src]):contains(edge.create)").text().split("\n");$.each(lines,function(index,line){var matchs=line.match(/var cc = '(.*)'/);if(matchs!==null){debug(matchs[1]);$("#over").remove();$("#vid_real").html(matchs[1]);debug("Not Ajax just parse coding & Changed Content");}});}};var getjetso_com=function(){debug('Init getjetso_com class');this.run=function(){debug('Strat run');var $post_block=$(".viewthread:first-child .postmessage .t_msgfont");var pid=$post_block.attr("id").replace("postmessage_","");debug("Block: "+$post_block);debug("PID: "+pid);ajax_it("http://"+window.location.host+"/forum/viewthread.php","action=paging&pid="+pid+"&inajax=1","xml").success(function(xml_doc){debug(xml_doc);var content=$("root",xml_doc).text();debug(content);$post_block.html(content);debug("Ended Ajax & Changed Content");});}};var www_hacken_cc=function(){debug('Init hacken_cc class');this.run=function(){debug('Strat run');var tid=window.location.href.match(/thread-(\d+)/)[1];ajax_it("http://"+window.location.host+"/bbs/plugins/fblike/like.php","tid="+tid+"&action=like&inajax=1","xml").success(function(xml_doc){debug(xml_doc);$.get(window.location.href,function(html){var content=$(".showhide",html).html();debug(content);var $locked=$(".locked:eq(0)");if($locked!=null){$locked.attr("class","showhide").prepend(content);}},"html");});debug("Not Ajax just hidden content & Changed Content");}}
var ideapit_net=function(){debug('Init ideapit_net class');this.run=function(){debug('Strat run');$("#hiden_content").show();debug("Not Ajax just hidden content & Changed Content");}};var jkforum_net=function(){debug('Init jkforum_net class');this.run=function(){debug('Strat run');var $post_block=$("table.fo:first-child").parent();var pid=$post_block.attr("id").replace("post_","");var tid=window.location.pathname.match(/thread-(\d+)-\d+-\d+\.html/)[1];debug("Block: "+$post_block);debug("PID: "+pid);ajax_it("http://"+window.location.host+"/forum.php","mod=viewthread&show=true&tid="+tid+"&viewpid="+pid+"&inajax=1","xml").success(function(xml_doc){debug(xml_doc);var content=$("root",xml_doc).text();debug(content);$post_block.html(content);debug("Ended Ajax & Changed Content");});}};var livdig_com=function(){debug('Init livdig_com class');this.run=function(){debug('Start run');$(".hidden-content").show();debug("Not Ajax just parse coding & Changed Content");}}
var loveu520_com=function(){debug('Init loveu520_com class');this.run=function(){debug('Strat run');var tid=window.location.href.match(/thread\-(\d+)\-/)[1];debug("tid: "+tid);ajax_it("http://"+window.location.host+"/ajax.php","action=GetFirstPostText&inajax=1&tid="+tid,"xml").success(function(xml_doc){debug(xml_doc);var content=$("root",xml_doc).text();debug(content);$("#firstmessage").html(content); var $subtitle=$(".subtitle");if($subtitle!=null){$subtitle.css("color","#F00").hide().slideDown("slow");}});debug("Not Ajax just hidden content & Changed Content");}};var mypagediy_com=function(){debug('Init mypagediy_com class');this.run=function(){debug('Strat run');$("#hidden-content").show();debug("Not Ajax just hidden content & Changed Content");}};var tenkucity_com=function(){debug('Init tenkucity_com class');this.run=function(){debug('Strat run');var $post_block=$("table.fo:first-child").parent();var pid=$post_block.attr("id").replace("post_","");var tid=window.location.pathname.match(/thread-(\d+)-\d+-\d+\.html/)[1];debug("Block: "+$post_block);debug("PID: "+pid);ajax_it("http://"+window.location.host+"/forum.php","mod=viewthread&display=true&tid="+tid+"&viewpid="+pid+"&inajax=1","xml").success(function(xml_doc){debug(xml_doc);var content=$("root",xml_doc).text();debug(content);$post_block.html(content);debug("Ended Ajax & Changed Content");});}};(function($){debug("Start JetIt");try{var hosts=window.location.host.split(".");hosts=clear_subdomain(hosts);debug(hosts)
var class_name=hosts.join("_");class_name=fix_prefix_class_name(class_name);debug(class_name);var instance=new window[class_name]();debug(instance);instance.run();}catch(e){if(DEBUG===false){alert("Not Supported site");}else{debug(e);}}
debug("Ended");})(jQuery);